#Pls Note: All notes starting with "From Qwen2.5-MAX" are purely just
#reference notes/#reminders for myself of how certain R functions work, 
#generated by the Qwen 2.5-MAX AI chatbot.

#Previously, I have conducted analyses on the subsets of data for K-Locus (Figure2A)
#and transporters (Figure 2B). Now, let's just do an analysis on data from 
#all the genes. I will copy over the code from my previous analyses and make
#appropriate adjustments


#Importing data
library(readr)

#let's set the working directory
bxg <- read_csv("allgenes.csv")
View(bxg)

#Formatting data
bxg = as.data.frame(bxg)
#Isolate our gene names from the 2nd column, starting at the 2rd row and
#continuing downward
genename=bxg[2:nrow(bxg),2]
genename

#Remove column one with the raw unannotated BAL062 gene names
bxg=bxg[,-1]

#Now let's isolate the logFC values
bxg=bxg[,1:ncol(bxg) %% 3==0]

headers=bxg[,]
bxg

bxg=matrix(as.numeric(unlist(bxg)),nrow(bxg),ncol(bxg))
head(bxg)

#Plot a Dendrogram to get a sense of the data
plot(hclust(dist(bxg)))
#Okay, something went wrong and we couldn't make a cluster. Let's trouble shoot
# Are there NAs?
sum(is.na(bxg))
# Any NaNs?
sum(is.nan(bxg))    
# Any Infs?
sum(is.infinite(bxg))

#Ok, we have some NAs. Let's turn them into 0's, which will indicate "no logFC"
bxg[is.na(bxg)] <- 0
#Let's try again now
plot(hclust(dist(bxg)))
#We have so many genes that the dendrogram is uninterpretable... Let's continue
#along the analysis and see what else we get

h=hclust(dist(t(bxg)))
plot(h)
h
#This dendrogram shows 10 distinct clusters. Are these just the 10 biocides?

#Fixing up the headers
headers
headers=as.character(headers)
is.character(headers)

rowSums(bxg)
#Caluclate the princible components of the cells
princomp(bxg)
#Skree plot to show PCA
plot(princomp(bxg)$sdev)
plot(princomp(bxg)$loadings,cex=0)
text(princomp(bxg)$loadings,labels=headers,xpd=NA)
#When considering the loadings, the Comp.1 vs Comp.2 graph is very messy

#Let's look at scores instead of loadings
plot(princomp(bxg)$scores,cex=0)
text(princomp(bxg)$scores,labels=genename,xpd=NA)

plot(factanal(bxg,factors=2,scores='regression')$scores,cex=0)
text(factanal(bxg,factors=2,scores='regression')$scores,labels=genename,xpd=NA)
factor=factanal(bxg,factors=4,scores='regression')
factor

factor$loadings

factor$scores
plot(factor$scores, cex=0)
text(factor$scores, cex=0.5, labels=genename)
#Okay thus plot is pretty interesting. We have three loose bunchings,
#plus a couple of outliers

#What happens if we change the numer of factors that we are considerng? That
#example used 4 factors. What if we reduced this to 3?
plot(factanal(bxg,factors=2,scores='regression')$scores,cex=0)
text(factanal(bxg,factors=2,scores='regression')$scores,labels=genename,xpd=NA)
factor=factanal(bxg,factors=3,scores='regression')
factor

factor$loadings

factor$scores
plot(factor$scores, cex=0)
text(factor$scores, cex=0.5, labels=genename)
#Okay yep the plot is pretty different. This MIGHT be more appropriate?
#Will need to read up on the impact of changing the factors in pca factor analysis

citation()