#Pls Note: All notes starting with "From Qwen2.5-MAX" are purely just
#reference notes/#reminders for myself of how certain R functions work, 
#generated by the Qwen 2.5-MAX AI chatbot.

#Work from meeting with John_20250326
#Importing data
library(readr)
getwd()
setwd("data/raw")
cells <- read_csv("cells.csv")
View(cells)

#Keep in mind!: The cells.csv dataset is solely genes from the K locus,
#which might just be limited to capsid-related proteins. In contrast,
#the Fig2B page of data has genes for transporters! I might be able to 
#use the same code to format this dataset for my liking

#Formatting data
cells = as.data.frame(cells)
genename=cells[3:nrow(cells),3]
genename
cells=cells[,1:ncol(cells) %% 3==2]
headers=cells[,]
headers
cells=cells[,-1]
cells=cells[-(1:2),]
cells=matrix(as.numeric(unlist(cells)),nrow(cells),ncol(cells))
head(cells)

#Plot a Dendrogram to get a sense of the data
plot(hclust(dist(cells)))

#From Qwen2.5-MAX: the dist() function will compute the distance between
#two points of data in the matrix. This will be the Euclidean distance between 
#each pair of rows in the dataset. This produces a symmetric matrix where each 
#entry represents the distance between two rows.The hclust() function 
#performs hierarchical clustering on the distance matrix generated by dist().

#We see two clusters. RHS has a group toward the bottom


h=hclust(dist(t(cells)))

#From Qwen2.5-MAX:The t() function transposes the cells dataset. 
#This swaps the rows and columns of the dataset.Now that the dataset has
#been tranposed, dist() will calculate the distance between columns (that
#between the independent varibales)
plot(h)
h
headers

#Investigating the hclust function
?hclust
headers=as.character(headers)
is.character(headers)

rowSums(cells)
#Caluclate the princible components of the cells
princomp(cells)
#Skree plot to show PCA
plot(princomp(cells)$sdev)
plot(princomp(cells)$loadings,cex=0)
text(princomp(cells)$loadings,labels=headers,xpd=NA)
#When considering the loadings, the Comp.1 vs Comp.2 graph is very messy

#Let's look at scores instead of loadings
plot(princomp(cells)$scores,cex=0)
text(princomp(cells)$scores,labels=genename,xpd=NA)

#From Qwen 2.5-Max:The factanal() function in R is used to perform Factor
#Analysis , a statistical method for modeling observed variables as linear
#combinations of underlying latent (unobserved) factors. Factor analysis 
#is often used to identify hidden patterns or structures in data, reduce 
#dimensionality, and explain correlations among multiple observed variables.
plot(factanal(cells,factors=2,scores='regression')$scores,cex=0)
text(factanal(cells,factors=2,scores='regression')$scores,labels=genename,xpd=NA)
factor=factanal(cells,factors=4,scores='regression')
factor

factor$loadings

factor$scores
plot(factor$scores, cex=0)
text(factor$scores, cex=0.5, labels=genename)
#By plotting the loadings of the factor analysis, we see a central cluster
#around co-ord 0,0, and a few genes scattered about the plot (specifically 
#htrB_1). Will be good to look at these "outlier" genes and see what's different
#about them

#Need to ask John about what these few last lines mean
is.numeric(cells)
is.matrix(cells)
sum(cells)
t(cells)

headers
colMeans(cells)
cells[,4]
sort(cells[,4])



