#Now let's run an anova using the new file generated by QwenAI

library(readr)
tav <- read_csv("transporters_anova.csv")
View(tav)
tav


#Let's start with a ONE-Way ANOVA (only consider nodulation group)

tav.model=aov(logFC~biocide, tav)
tav.model

#Test the model for ANOVA assumptions
#1) Homogeneity of Variance, via...
#Levene Test
library(car)

leveneTest(tav.model)
#Plot Residuals against Fitted values
plot(tav.model)
#Look to the Q-Q plot to assess normality of variance 

#Mostly okay, though not perfect. Let's run the ANOVA and see how it looks
anova(tav.model)

#ANOVA assumptions aren't met. So, let's try a Kruskal-Wallis test
library(curl)
kruskal.test(logFC~biocide, tav)

#Which groups differ? > TukeyHSD
TukeyHSD(tav.model, ordered=TRUE)

#Now let's look at the differences between genes
gav.model <- aov(logFC~gene_name, tav)
gav.model

#Test the model for ANOVA assumptions
#1) Homogeneity of Variance, via...
#Levene Test
library(car)

leveneTest(gav.model)
#Plot Residuals against Fitted values
plot(gav.model)
#Look to the Q-Q plot to assess normality of variance 

#Mostly okay, though not perfect. Let's run the ANOVA and see how it looks
anova(gav.model)

#ANOVA assumptions aren't met. So, let's try a Kruskal-Wallis test
library(curl)
kruskal.test(logFC~gene_name, gav)

#Which groups differ? > TukeyHSD
TukeyHSD(gav.model, ordered=TRUE)

#Output is very large. So, let's send the output to a csv file (QwenAI code)

# Extract the comparisons from the first term (assuming only one factor)
# You may need to adjust the index or loop through all factors

# Run TukeyHSD
tukey_results <- TukeyHSD(gav.model, ordered = TRUE)

# Get the results for the first factor (e.g., "factor_name")
tukey_df <- as.data.frame(tukey_results[[1]])

# Add row names as a column (the pairwise comparisons)
tukey_df$comparison <- rownames(tukey_df)

# Reorder columns to make it more readable
tukey_df <- tukey_df[, c("comparison", "lwr", "upr", "p adj")]

# View the result
print(tukey_df)

# Write to CSV
write.csv(tukey_df, "tukey_hsd_results.csv", row.names = FALSE)
